# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Get Help. Give Help. Get Informed. | norcalfires.fyi 
email: neil@ruudmedia.com
description: >- # this means to ignore newlines until "baseurl:"
  A central resource for help, donations, news, and other resources pertaining to the norcal firestorms that have devastated the region.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://norcalfires.fyi" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: nomorefuckinguns
#github_username:  jekyll

# Build settings
markdown: kramdown
logo: 
sass:
    style: compressed
    sass_dir: _scss
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll_get:
  - data: napasheriffnixle
    json: 'https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fagency.nixle.com%2Fpubs%2Ffeeds%2Flatest%2F1085'
  - data: sonomasheriffnixle
    json: 'https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fagency.nixle.com%2Fpubs%2Ffeeds%2Flatest%2F235'
  - data: currentfires
    json: 'https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.fire.ca.gov%2Frss%2Frss.xml'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
